apiVersion: v1
kind: ConfigMap
metadata:
  name: im-demo-config
  namespace: demo-im
data:
  PORT: "3001"
  CORS_ORIGIN: "https://im-demo.connected-cloud.io"
  AKAMAI_PROPERTY_HOSTNAME: "im-demo.connected-cloud.io"
  EDGERC_PATH: "/etc/akamai/.edgerc"
  EDGERC_SECTION: "default"
